version: "3"

networks:
  druiddb-docker:

services:
  zookeeper:
    image: zookeeper
    networks:
      - druiddb-docker

  derby:
    image: adito/apache-derby
    networks:
      - druiddb-docker

  kafka:
    image: ches/kafka:0.9.0.1
    networks:
      - druiddb-docker
    depends_on:
      - zookeeper
    environment:
      ZOOKEEPER_IP: zookeeper

  broker:
    image: andremleblanc/druid-broker:0.9.2
    build: ./druid-broker
    networks:
      - druiddb-docker
    ports:
      - '38082:8082'
    depends_on:
      - zookeeper

  coordinator:
    image: andremleblanc/druid-coordinator:0.9.2
    build: ./druid-coordinator
    networks:
      - druiddb-docker
    ports:
      - '38081:8081'
    depends_on:
      - zookeeper

  historical:
    image: andremleblanc/druid-historical:0.9.2
    build: ./druid-historical
    networks:
      - druiddb-docker
    ports:
      - '38083:8083'
    depends_on:
      - zookeeper

  middlemanager:
    image: andremleblanc/druid-middlemanager:0.9.2
    build: ./druid-middlemanager
    networks:
      - druiddb-docker
    depends_on:
      - zookeeper

  overlord:
    image: andremleblanc/druid-overlord:0.9.2
    build: ./druid-overlord
    networks:
      - druiddb-docker
    ports:
      - '38090:8090'
    depends_on:
      - zookeeper
      - derby
