version: "3"

networks:
  druiddb-docker:

volumes:
  druid-fs:

services:
  zookeeper:
    image: zookeeper:3.4
    # hostname: localhost
    networks:
      - druiddb-docker
    ports:
      - '2181:2181'

  derby:
    image: adito/apache-derby
    networks:
      - druiddb-docker

  # kafka:
  #   image: ches/kafka:0.10.2.1
  #   hostname: localhost
  #   networks:
  #     - druiddb-docker
  #   ports:
  #     - '7203:7203'
  #     - '9092:9092'
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     ZOOKEEPER_IP: zookeeper
  #     # KAFKA_ADVERTISED_HOST_NAME: kafka Note: setting this prevented writing to Kafka

  kafka:
    image: wurstmeister/kafka:0.10.2.1
    # hostname: localhost
    networks:
      - druiddb-docker
    ports:
      - '7203:7203'
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.6
      # KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  broker:
    image: andremleblanc/druid-broker:0.9.2
    build: ./druid-broker
    # hostname: broker
    networks:
      - druiddb-docker
    ports:
      - '8082:8082'
    depends_on:
      - zookeeper
      - derby
      - kafka
    volumes:
      - druid-fs:/druid-0.10.0/var/druid/

  coordinator:
    image: andremleblanc/druid-coordinator:0.9.2
    build: ./druid-coordinator
    # hostname: coordinator
    networks:
      - druiddb-docker
    ports:
      - '8081:8081'
    depends_on:
      - zookeeper
      - derby
      - kafka
    volumes:
      - druid-fs:/druid-0.10.0/var/druid/

  historical:
    image: andremleblanc/druid-historical:0.9.2
    build: ./druid-historical
    # hostname: historical
    networks:
      - druiddb-docker
    ports:
      - '8083:8083'
    depends_on:
      - zookeeper
      - derby
      - kafka
    volumes:
      - druid-fs:/druid-0.10.0/var/druid/

  middlemanager:
    image: andremleblanc/druid-middlemanager:0.9.2
    build: ./druid-middlemanager
    # hostname: middlemanager
    networks:
      - druiddb-docker
    depends_on:
      - zookeeper
      - derby
      - kafka
    volumes:
      - druid-fs:/druid-0.10.0/var/druid/

  overlord:
    image: andremleblanc/druid-overlord:0.9.2
    build: ./druid-overlord
    # hostname: overlord
    networks:
      - druiddb-docker
    ports:
      - '8090:8090'
    depends_on:
      - zookeeper
      - kafka
      - derby
    volumes:
      - druid-fs:/druid-0.10.0/var/druid/
