version: "3"

networks:
  druiddb-docker:

services:
  zookeeper:
    image: zookeeper:3.4
    hostname: localhost
    networks:
      - druiddb-docker
    ports:
      - '2181:2181'

  derby:
    image: adito/apache-derby
    networks:
      - druiddb-docker

  kafka:
    image: ches/kafka:0.10.2.1
    hostname: localhost
    networks:
      - druiddb-docker
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      ZOOKEEPER_IP: zookeeper

  broker:
    image: andremleblanc/druid-broker:0.9.2
    build: ./druid-broker
    hostname: localhost
    networks:
      - druiddb-docker
    ports:
      - '8082:8082'
    depends_on:
      - zookeeper
      - derby
      - kafka

  coordinator:
    image: andremleblanc/druid-coordinator:0.9.2
    build: ./druid-coordinator
    hostname: localhost
    networks:
      - druiddb-docker
    ports:
      - '8081:8081'
    depends_on:
      - zookeeper
      - derby
      - kafka

  historical:
    image: andremleblanc/druid-historical:0.9.2
    build: ./druid-historical
    hostname: localhost
    networks:
      - druiddb-docker
    ports:
      - '8083:8083'
    depends_on:
      - zookeeper
      - derby
      - kafka

  middlemanager:
    image: andremleblanc/druid-middlemanager:0.9.2
    build: ./druid-middlemanager
    hostname: localhost
    networks:
      - druiddb-docker
    depends_on:
      - zookeeper
      - derby
      - kafka

  overlord:
    image: andremleblanc/druid-overlord:0.9.2
    build: ./druid-overlord
    hostname: localhost
    networks:
      - druiddb-docker
    ports:
      - '8090:8090'
    depends_on:
      - zookeeper
      - kafka
      - derby
